### ISSUE TITLE
RShiny- DT::renderDataTable works locally but disconnect from server when using reactive function (Sortable: bucketlist - drag and drop)

### ISSUE THREAD

**Issue by Vini875** [rstudio/sortable#61] opened 2020-08-12 10:54 UTC
Hi All,

I am facing issues with DT::renderDataTable with reactive function (which is used to select Drag and Drop columns as and when Business team want to filter selected columns to show on UI). It works locally on console but disconnect when I am running on RServer using the web link at the point when it was trying to populate dataframe on UI. 

I have checked the version of sortable package on server and whats loaded in by code and is same, so this doesn't looks to be an issue.

If anyone has any idea to fix this issue. I appreciate your responses.

**Comment by andrie** [comment] 2020-08-12 11:17
This seems like a duplicate of #60

**Comment by andrie** [comment] 2020-08-12 11:21
I'm closing this as a duplicate of #60.  Please provide a minimal reproducible example shiny app in issue #60.

**Closed by andrie** 2020-08-12 11:21 UTC
